services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres_db # Nome do container para fácil identificação
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nest-car
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: